package com.agilityio.employeeservice.models;

import lombok.*;

import javax.validation.Valid;
import java.util.ArrayList;
import java.util.List;

@Getter
@Setter
@ToString
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode
@Builder
public class Employee {

    /**
     * The employee id generated by the system
     */
    private String id;

    /**
     * The unique department id for the list of employees
     */
    private String departmentId;

    /**
     * List of employees of the specified department
     */
    @Valid
    private List<EmployeeItem> employeeItems = new ArrayList<>();
}
